name: Output for a Job Demo

on:
  push:
    branches:
      - main
  
run-name: "::notice Workflow run for branch ${{ github.ref_name }}"

jobs:
  first_job:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - id: step1
        run: echo "test=hello" >> "$GITHUB_OUTPUT"
      - id: step2
        run: echo "test=wold" >> "$GITHUB_OUTPUT"
  second_job:
    runs-on: ubuntu-latest
    needs: first_job
    steps:
      - env:
          OUTPUT1: ${{needs.first_job.outputs.output1}}
          OUTPUT2: ${{needs.first_job.outputs.output2}}
        run: echo "$OUTPUT1 $OUTPUT2"
    
